### ISSUE TITLE
Error in installing ubuntu in termux

### ISSUE THREAD

**Issue by Smarty10** [MFDGaming/ubuntu-in-termux#53]
I have done everything thing, proot git ,wget..installed Ubuntu but when i try to run that file it says........
proot warning: can't sanitize binding "ubuntu-fs/tmp": No such file or directory proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory                                                                              proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs, cwd = /, $PATH=(null))
fatal error: see `proot --help`.

Plzzz help

**Comment by eyachay** [comment]
Greetings,
I emulate your problem. Try the next solution.
Ubuntu changed the version of the base iso. So you must change the ubuntu version in the bash script.
Instead of :
UBUNTU_VERSION=20.04
write this:
UBUNTU_VERSION=20.04.1
In case it is solved please give me a like and share.

**Comment by artemisfowl004** [comment]
> Greetings,
> I emulate your problem. Try the next solution.
> Ubuntu changed the version of the base iso. So you must change the ubuntu version in the bash script.
> Instead of :
> UBUNTU_VERSION=20.04
> write this:
> UBUNTU_VERSION=20.04.1
> In case it is solved please give me a like and share.

Thanks this Worked

**Comment by MFDGaming** [comment]
@eyachay i merged your pull, sorry for the inconvenience

**Comment by Smarty10** [comment]
> Greetings,
> I emulate your problem. Try the next solution.
> Ubuntu changed the version of the base iso. So you must change the ubuntu version in the bash script.
> Instead of :
> UBUNTU_VERSION=20.04
> write this:
> UBUNTU_VERSION=20.04.1
> In case it is solved please give me a like and share.

Still facing problems...can u help??it says...

proot warning: can't sanitize binding "ubuntu-fs/tmp": No such file or directory
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs, cwd = /, $PATH=(null))
fatal error: see `proot --help`.

**Comment by Smarty10** [comment]
> @eyachay i merged your pull, sorry for the inconvenience

Still facing problems pllzzzz help.. im stuck with this issue.....it says.....
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/ubuntu-in-termux/termux-ubuntu/ubuntu-fs, cwd = /, $PATH=(null))
fatal error: see `proot --help`.

**Comment by Smarty10** [comment]
> @eyachay i merged your pull, sorry for the inconvenience

Thanks. I reinstalled your ubuntu. Now it works...thanks alot👍👍👍
